### ISSUE TITLE
Not loading recipes when using static folder in a docker container

### ISSUE THREAD

**Issue by DBHeise** [DBHeise/CyberSaucier#2]
using the following docker-compose.yml:
```
version:    '3'
services:
    cybersaucier:
        image: crazydave42/cybersaucier:latest
        volumes:
            - F:/tmp/recipe:/data/recipe
        ports:
            - 7000:7000
        environment: 
            - CYBERSAUCIER_RecipeFolder=/data/recipe
            - CYBERSAUCIER_RecipeGit=""
            - CYBERSAUCIER_LogLevel=0
```
Then set a single recipe in F:/tmp/recipe

it does not get loaded
